param(
  [Parameter(Mandatory = $true)]
  [string]$OutputRoot
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$sourceSkillsRoot = Join-Path $repoRoot ".claude/skills"
$targetSkillsRoot = Join-Path $OutputRoot ".codex/skills"

if (-not (Test-Path $sourceSkillsRoot)) {
  throw "Source skills directory not found: $sourceSkillsRoot"
}

New-Item -ItemType Directory -Force $targetSkillsRoot | Out-Null

# Copy skill folders and files.
Get-ChildItem $sourceSkillsRoot -Directory | ForEach-Object {
  $skillName = $_.Name
  $src = $_.FullName
  $dst = Join-Path $targetSkillsRoot $skillName
  New-Item -ItemType Directory -Force $dst | Out-Null
  Copy-Item -Path (Join-Path $src "*") -Destination $dst -Recurse -Force
}

# Copy shared root docs for context in the Codex repo.
Copy-Item (Join-Path $repoRoot "README.md") (Join-Path $OutputRoot "README.upstream.md") -Force
Copy-Item (Join-Path $repoRoot "CLAUDE.md") (Join-Path $OutputRoot "CLAUDE.upstream.md") -Force

# Create Codex-specific README with explicit experimental warning.
$readme = @"
# Swarm Quickstart Skills (Codex)

> [!WARNING]
> Experimental autogenerated mirror. This repository is generated from `ethersphere/swarm-quickstart-skills`, has not been manually tested, and may contain issues.

This repository mirrors Swarm quickstart skills for Codex consumption.

## Source of Truth

- Canonical source: `https://github.com/ethersphere/swarm-quickstart-skills`
- Generated from: `.claude/skills/**/SKILL.md`
- Target layout here: `.codex/skills/**/SKILL.md`

## Regeneration

Changes should be made in the source repository. This repository is overwritten by automation.
"@
Set-Content -Path (Join-Path $OutputRoot "README.md") -Value $readme

# Keep repository tidy by ensuring no Claude skills are carried over.
$claudeDirInTarget = Join-Path $OutputRoot ".claude"
if (Test-Path $claudeDirInTarget) {
  Remove-Item -Recurse -Force $claudeDirInTarget
}

